wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.40.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1721122499.0
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 12
      - 45
      - 49
      - 51
      - 55
      - 71
      - 105
      2:
      - 1
      - 2
      - 3
      - 11
      - 12
      - 45
      - 49
      - 51
      - 55
      - 71
      - 105
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.16.6
      6: 4.40.1
      8:
      - 1
      - 5
      13: linux-x86_64
