wandb_version: 1

model_name:
  desc: null
  value: gpt2-small
model_class_name:
  desc: null
  value: HookedTransformer
hook_name:
  desc: null
  value: blocks.8.hook_resid_pre
hook_eval:
  desc: null
  value: NOT_IN_USE
hook_layer:
  desc: null
  value: 8
hook_head_index:
  desc: null
  value: null
dataset_path:
  desc: null
  value: apollo-research/Skylion007-openwebtext-tokenizer-gpt2
dataset_trust_remote_code:
  desc: null
  value: true
streaming:
  desc: null
  value: true
is_dataset_tokenized:
  desc: null
  value: true
context_size:
  desc: null
  value: 256
use_cached_activations:
  desc: null
  value: false
cached_activations_path:
  desc: null
  value: null
architecture:
  desc: null
  value: standard
d_in:
  desc: null
  value: 768
d_sae:
  desc: null
  value: 24576
b_dec_init_method:
  desc: null
  value: geometric_median
expansion_factor:
  desc: null
  value: 32
activation_fn:
  desc: null
  value: relu
normalize_sae_decoder:
  desc: null
  value: true
noise_scale:
  desc: null
  value: 0.0
from_pretrained_path:
  desc: null
  value: null
apply_b_dec_to_input:
  desc: null
  value: true
decoder_orthogonal_init:
  desc: null
  value: false
decoder_heuristic_init:
  desc: null
  value: false
init_encoder_as_decoder_transpose:
  desc: null
  value: false
n_batches_in_buffer:
  desc: null
  value: 20
training_tokens:
  desc: null
  value: 10000000
finetuning_tokens:
  desc: null
  value: 0
store_batch_size_prompts:
  desc: null
  value: 32
train_batch_size_tokens:
  desc: null
  value: 4096
normalize_activations:
  desc: null
  value: none
device:
  desc: null
  value: cuda
act_store_device:
  desc: null
  value: cuda
seed:
  desc: null
  value: 42
dtype:
  desc: null
  value: float32
prepend_bos:
  desc: null
  value: true
autocast:
  desc: null
  value: false
autocast_lm:
  desc: null
  value: false
compile_llm:
  desc: null
  value: false
llm_compilation_mode:
  desc: null
  value: null
compile_sae:
  desc: null
  value: false
sae_compilation_mode:
  desc: null
  value: null
adam_beta1:
  desc: null
  value: 0
adam_beta2:
  desc: null
  value: 0.999
mse_loss_normalization:
  desc: null
  value: null
l1_coefficient:
  desc: null
  value: 0.005
lp_norm:
  desc: null
  value: 1.0
scale_sparsity_penalty_by_decoder_norm:
  desc: null
  value: false
l1_warm_up_steps:
  desc: null
  value: 0
lr:
  desc: null
  value: 1.0e-05
lr_scheduler_name:
  desc: null
  value: cosine
lr_warm_up_steps:
  desc: null
  value: 0
lr_end:
  desc: null
  value: 1.0000000000000002e-06
lr_decay_steps:
  desc: null
  value: 0
n_restart_cycles:
  desc: null
  value: 1
finetuning_method:
  desc: null
  value: null
use_ghost_grads:
  desc: null
  value: false
feature_sampling_window:
  desc: null
  value: 2000
dead_feature_window:
  desc: null
  value: 1000
dead_feature_threshold:
  desc: null
  value: 1.0e-08
n_eval_batches:
  desc: null
  value: 10
eval_batch_size_prompts:
  desc: null
  value: null
log_to_wandb:
  desc: null
  value: true
log_activations_store_to_wandb:
  desc: null
  value: false
log_optimizer_state_to_wandb:
  desc: null
  value: false
wandb_project:
  desc: null
  value: sae_finetuning_r_score
wandb_id:
  desc: null
  value: null
run_name:
  desc: null
  value: 24576-L1-0.005-LR-1e-05-Tokens-1.000e+07
wandb_entity:
  desc: null
  value: null
wandb_log_frequency:
  desc: null
  value: 10
eval_every_n_wandb_logs:
  desc: null
  value: 100
resume:
  desc: null
  value: false
n_checkpoints:
  desc: null
  value: 5
checkpoint_path:
  desc: null
  value: ./checkpoints/j1xmo6ii
verbose:
  desc: null
  value: true
model_kwargs:
  desc: null
  value: {}
model_from_pretrained_kwargs:
  desc: null
  value: {}
sae_lens_version:
  desc: null
  value: 3.7.0
sae_lens_training_version:
  desc: null
  value: 3.7.0
tokens_per_buffer:
  desc: null
  value: 20971520
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.40.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1721082782.0
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 12
      - 45
      - 49
      - 51
      - 55
      - 71
      - 105
      2:
      - 1
      - 2
      - 3
      - 11
      - 12
      - 45
      - 49
      - 51
      - 55
      - 71
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.16.6
      6: 4.40.1
      8:
      - 1
      - 5
      13: linux-x86_64
